version: "3.9"
services:
  mailing-service:
    depends_on:
      - postgres
    build:
      context: .
      args:
        image: golang:1.22
        dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_ADDRESS=postgres:5432

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mailing"
      PGDATA: /data/postgres
    volumes:
       - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
